/* eslint-disable react/no-unknown-property */
import React from 'react'
import { Provider } from 'react-redux'
import { ModalsController } from '@components/ModalsController/ModalsController'
import Layout, { Layouts } from '@layouts/index'
import store from '@redux/store'
import { NextComponentType, NextPageContext } from 'next'
import { Roboto } from 'next/font/google'
import Head from 'next/head'

import '@styles/globals.css'

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

interface IAppProps {
  Component: NextComponentType<NextPageContext, never> & {
    Layout: keyof typeof Layouts
  }
  pageProps: JSX.IntrinsicAttributes
}

const App = ({ Component, pageProps }: IAppProps) => {
  const HierarchicalLayout = Layouts[Component.Layout]

  return (
    <>
      <style
        jsx
        global
      >
        {`
          html {
            font-family: ${roboto.style.fontFamily};
          }
        `}
      </style>
      <Head>
        <title>BEP Armenia</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <Provider store={store}>
          <Layout>
            {HierarchicalLayout ? (
              <HierarchicalLayout>
                <Component {...pageProps} />
              </HierarchicalLayout>
            ) : (
              <Component {...pageProps} />
            )}
          </Layout>
          <ModalsController />
        </Provider>
      </main>
    </>
  )
}

export default App
