import { NextComponentType, NextPage, NextPageContext } from 'next'
import type { AppProps } from 'next/app'
import { Roboto } from 'next/font/google'
import Head from 'next/head'

import { LayoutKeys, Layouts } from '@/layouts'

import '@/styles/globals.css'

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export type NextPageWithLayout<P = object, IP = P> = NextPage<P, IP> & {
  Layout?: LayoutKeys
}

type AppPropsWithLayout = AppProps & {
  Component: NextComponentType<NextPageContext, never> & {
    Layout: LayoutKeys
  }
}

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const Layout = Layouts[Component.Layout] ?? ((page) => page)
  return (
    <>
      <Head>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${roboto.variable} font-sans`}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </main>
    </>
  )
}
