import React from 'react'
import Layout, { Layouts } from '@layouts/index'
import { NextComponentType, NextPageContext } from 'next'
import { Roboto } from 'next/font/google'
import Head from 'next/head'

import '@styles/globals.css'

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

interface IAppProps {
  Component: NextComponentType<NextPageContext, never> & {
    Layout: keyof typeof Layouts
  }
  pageProps: JSX.IntrinsicAttributes
}

const App = ({ Component, pageProps }: IAppProps) => {
  const ChildLayout = Layouts[Component.Layout]

  return (
    <>
      <Head>
        <title>BEP Armenia</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${roboto.variable} font-sans`}>
        {ChildLayout ? (
          <ChildLayout>
            <Component {...pageProps} />
          </ChildLayout>
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </main>
    </>
  )
}

export default App
