name: Build
run-name: ${{ github.workflow }}-${{ github.actor }}-${{ github.event.head_commit.message}}
on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - master

jobs:
  run-audit-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
          with:
            version: 6.0.2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: pnpm build

      - name: Run Audit CI
        run: yarn audit
